# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.database.pvc.enabled }}
{{- if .Values.database.pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-database-pvc
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - {{ .Values.database.pvc.accessMode }}
  {{- if .Values.database.pvc.storageClassName }}
  storageClassName: {{ .Values.database.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.pvc.size }}
{{- end }}
{{- end }}

